export const TrainingAnalyticsConfig = {
  speedControlMoves: [
    'Tailwind',
    'Trick Room',
    'Sticky Web',
    'Icy Wind',
    'Electroweb',
    'Bulldoze',
    'Glaciate',
    'Bleakwind Storm',
    'Rock Tomb',
    'Low Sweep',
    'Mud Shot',
    'Drum Beating',
    'Pounce',
    'Constrict',
    'Bubble',
    'Bubble Beam',
    'Scary Face',
    'Cotton Spore',
    'String Shot',
    'Screech',
    'Thunder Wave',
    'Glare',
    'Stun Spore',
    'Nuzzle',
    'Body Slam',
    'Zap Cannon',
    'Quash',
    'After You',
    'Speed Swap',
    'Ally Switch',
  ],
};
