import { mkdir, readdir, readFile, stat, writeFile } from 'fs/promises';
import path from 'path';

const grepFilesInDirectory = async (directoryPath: string) => {
  const modules = new Set<string>();

  const files = await readdir(directoryPath);
  const promises = files.map(async (file) => {
    const filePath = path.join(directoryPath, file);
    const stats = await stat(filePath);
    if (stats.isFile()) {
      const data = await readFile(filePath, 'utf8');
      const lines = data.split('\n');
      lines.forEach((line) => {
        const match = line.match(/'antd\/es\/(?<module>.+?)';/);
        if (match) {
          const antdModule = match.groups?.['module'];
          if (antdModule !== undefined) {
            modules.add(antdModule);
          }
        }
      });
    }
    if (stats.isDirectory()) {
      const submodules = await grepFilesInDirectory(filePath);
      submodules.forEach((module) => modules.add(module));
    }
  });

  await Promise.all(promises);

  return modules;
};

const createMock = async (module: string) => {
  const mock = `/**
 * @file This file is automatically generated. Do not modify
 */

import * as mock from 'antd/lib/${module}';

module.exports = mock;
  `;
  const filePath = `__mocks__/antd/es/${module}.ts`;
  const directoryPath = path.dirname(filePath);
  await mkdir(directoryPath, { recursive: true });
  await writeFile(filePath, mock);
};

const main = async () => {
  console.log('Generating mocks...');
  const modulesFromApp = await grepFilesInDirectory('./app');
  const modulesFromSrc = await grepFilesInDirectory('./src');
  const modules = new Set([...modulesFromApp, ...modulesFromSrc]);
  const promises = Array.from(modules).map((module) => createMock(module));
  await Promise.all(promises);
  console.log(`Generated ${promises.length} mocks`);
};

main()
  .then(() => console.log('Done'))
  .catch((err) => console.error('Failed', err));
